### ISSUE TITLE
Crashes on entering License (ISC)

### ISSUE THREAD

**Issue by uPaymeiFixit** [dudeofawesome/generator-uebersicht#1]
Crashes when entering `License (ISC)`. I have tried GPLv2, GPL, and just hitting enter. Same error every time. Here is the error and a screenshot:

```
TypeError: cb is not a function
    at /usr/local/lib/node_modules/generator-uebersicht/node_modules/github-username/index.js:30:3
    at process._tickCallback (node.js:401:9)

events.js:154
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-uebersicht/generators/app/templates/.gitignore
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-uebersicht/node_modules/mem-fs-editor/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-uebersicht/node_modules/mem-fs-editor/actions/copy.js:23:17)
    at module.exports.yeoman.generators.Base.extend.writing (/usr/local/lib/node_modules/generator-uebersicht/generators/app/index.js:63:21)
    at /usr/local/lib/node_modules/generator-uebersicht/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

![Screenshot](https://lh4.googleusercontent.com/-f-S60nYado8/VrNq2Wa1SPI/AAAAAAAAoc4/gC0sERPaPYo/w737-h1161-no/2016-02-04.png)

**Comment by dudeofawesome** [comment]
This was happening because NPM was renaming the template's .gitignore file to .npmignore.

I've fixed this in [v1.1.2](https://github.com/dudeofawesome/generator-uebersicht/releases/tag/v1.1.2)
